// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package/types/protobuf.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParserStatus_Status int32

const (
	ParserStatus_NIL     ParserStatus_Status = 0
	ParserStatus_READY   ParserStatus_Status = 1
	ParserStatus_WORKING ParserStatus_Status = 2
	ParserStatus_DONE    ParserStatus_Status = 3
)

var ParserStatus_Status_name = map[int32]string{
	0: "NIL",
	1: "READY",
	2: "WORKING",
	3: "DONE",
}

var ParserStatus_Status_value = map[string]int32{
	"NIL":     0,
	"READY":   1,
	"WORKING": 2,
	"DONE":    3,
}

func (x ParserStatus_Status) String() string {
	return proto.EnumName(ParserStatus_Status_name, int32(x))
}

func (ParserStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{0, 0}
}

type ParserType_Type int32

const (
	ParserType_NIL ParserType_Type = 0
)

var ParserType_Type_name = map[int32]string{
	0: "NIL",
}

var ParserType_Type_value = map[string]int32{
	"NIL": 0,
}

func (x ParserType_Type) String() string {
	return proto.EnumName(ParserType_Type_name, int32(x))
}

func (ParserType_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{1, 0}
}

type ClientResultCode_Code int32

const (
	ClientResultCode_OK    ClientResultCode_Code = 0
	ClientResultCode_READY ClientResultCode_Code = 1
	ClientResultCode_ERROR ClientResultCode_Code = 9
)

var ClientResultCode_Code_name = map[int32]string{
	0: "OK",
	1: "READY",
	9: "ERROR",
}

var ClientResultCode_Code_value = map[string]int32{
	"OK":    0,
	"READY": 1,
	"ERROR": 9,
}

func (x ClientResultCode_Code) String() string {
	return proto.EnumName(ClientResultCode_Code_name, int32(x))
}

func (ClientResultCode_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{2, 0}
}

type RequestType_Type int32

const (
	RequestType_NIL         RequestType_Type = 0
	RequestType_CLIENT_INIT RequestType_Type = 1
	RequestType_PARSER_URL  RequestType_Type = 10
)

var RequestType_Type_name = map[int32]string{
	0:  "NIL",
	1:  "CLIENT_INIT",
	10: "PARSER_URL",
}

var RequestType_Type_value = map[string]int32{
	"NIL":         0,
	"CLIENT_INIT": 1,
	"PARSER_URL":  10,
}

func (x RequestType_Type) String() string {
	return proto.EnumName(RequestType_Type_name, int32(x))
}

func (RequestType_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{3, 0}
}

type ResponseType_Type int32

const (
	ResponseType_ParserResult ResponseType_Type = 0
	ResponseType_PostResult   ResponseType_Type = 1
	ResponseType_ErrorResult  ResponseType_Type = 9
)

var ResponseType_Type_name = map[int32]string{
	0: "ParserResult",
	1: "PostResult",
	9: "ErrorResult",
}

var ResponseType_Type_value = map[string]int32{
	"ParserResult": 0,
	"PostResult":   1,
	"ErrorResult":  9,
}

func (x ResponseType_Type) String() string {
	return proto.EnumName(ResponseType_Type_name, int32(x))
}

func (ResponseType_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{4, 0}
}

type ParserStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserStatus) Reset()         { *m = ParserStatus{} }
func (m *ParserStatus) String() string { return proto.CompactTextString(m) }
func (*ParserStatus) ProtoMessage()    {}
func (*ParserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{0}
}

func (m *ParserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserStatus.Unmarshal(m, b)
}
func (m *ParserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserStatus.Marshal(b, m, deterministic)
}
func (m *ParserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserStatus.Merge(m, src)
}
func (m *ParserStatus) XXX_Size() int {
	return xxx_messageInfo_ParserStatus.Size(m)
}
func (m *ParserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ParserStatus proto.InternalMessageInfo

type ParserType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserType) Reset()         { *m = ParserType{} }
func (m *ParserType) String() string { return proto.CompactTextString(m) }
func (*ParserType) ProtoMessage()    {}
func (*ParserType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{1}
}

func (m *ParserType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserType.Unmarshal(m, b)
}
func (m *ParserType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserType.Marshal(b, m, deterministic)
}
func (m *ParserType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserType.Merge(m, src)
}
func (m *ParserType) XXX_Size() int {
	return xxx_messageInfo_ParserType.Size(m)
}
func (m *ParserType) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserType.DiscardUnknown(m)
}

var xxx_messageInfo_ParserType proto.InternalMessageInfo

type ClientResultCode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResultCode) Reset()         { *m = ClientResultCode{} }
func (m *ClientResultCode) String() string { return proto.CompactTextString(m) }
func (*ClientResultCode) ProtoMessage()    {}
func (*ClientResultCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{2}
}

func (m *ClientResultCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResultCode.Unmarshal(m, b)
}
func (m *ClientResultCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResultCode.Marshal(b, m, deterministic)
}
func (m *ClientResultCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResultCode.Merge(m, src)
}
func (m *ClientResultCode) XXX_Size() int {
	return xxx_messageInfo_ClientResultCode.Size(m)
}
func (m *ClientResultCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResultCode.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResultCode proto.InternalMessageInfo

type RequestType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestType) Reset()         { *m = RequestType{} }
func (m *RequestType) String() string { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()    {}
func (*RequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{3}
}

func (m *RequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestType.Unmarshal(m, b)
}
func (m *RequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestType.Marshal(b, m, deterministic)
}
func (m *RequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestType.Merge(m, src)
}
func (m *RequestType) XXX_Size() int {
	return xxx_messageInfo_RequestType.Size(m)
}
func (m *RequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestType.DiscardUnknown(m)
}

var xxx_messageInfo_RequestType proto.InternalMessageInfo

type ResponseType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseType) Reset()         { *m = ResponseType{} }
func (m *ResponseType) String() string { return proto.CompactTextString(m) }
func (*ResponseType) ProtoMessage()    {}
func (*ResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{4}
}

func (m *ResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseType.Unmarshal(m, b)
}
func (m *ResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseType.Marshal(b, m, deterministic)
}
func (m *ResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseType.Merge(m, src)
}
func (m *ResponseType) XXX_Size() int {
	return xxx_messageInfo_ResponseType.Size(m)
}
func (m *ResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseType proto.InternalMessageInfo

type MatchRule struct {
	Rule                 string   `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Keys                 string   `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	Values               string   `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchRule) Reset()         { *m = MatchRule{} }
func (m *MatchRule) String() string { return proto.CompactTextString(m) }
func (*MatchRule) ProtoMessage()    {}
func (*MatchRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{5}
}

func (m *MatchRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRule.Unmarshal(m, b)
}
func (m *MatchRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRule.Marshal(b, m, deterministic)
}
func (m *MatchRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRule.Merge(m, src)
}
func (m *MatchRule) XXX_Size() int {
	return xxx_messageInfo_MatchRule.Size(m)
}
func (m *MatchRule) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRule.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRule proto.InternalMessageInfo

func (m *MatchRule) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *MatchRule) GetKeys() string {
	if m != nil {
		return m.Keys
	}
	return ""
}

func (m *MatchRule) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type Request struct {
	Status               ParserStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=types.ParserStatus_Status" json:"status,omitempty"`
	Parser               ParserType_Type     `protobuf:"varint,2,opt,name=parser,proto3,enum=types.ParserType_Type" json:"parser,omitempty"`
	Type                 RequestType_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=types.RequestType_Type" json:"type,omitempty"`
	Host                 string              `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string              `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MatchRules           []*MatchRule        `protobuf:"bytes,6,rep,name=matchRules,proto3" json:"matchRules,omitempty"`
	PathRule             string              `protobuf:"bytes,7,opt,name=pathRule,proto3" json:"pathRule,omitempty"`
	NeedMatchRule        string              `protobuf:"bytes,8,opt,name=needMatchRule,proto3" json:"needMatchRule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{6}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetStatus() ParserStatus_Status {
	if m != nil {
		return m.Status
	}
	return ParserStatus_NIL
}

func (m *Request) GetParser() ParserType_Type {
	if m != nil {
		return m.Parser
	}
	return ParserType_NIL
}

func (m *Request) GetType() RequestType_Type {
	if m != nil {
		return m.Type
	}
	return RequestType_NIL
}

func (m *Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetMatchRules() []*MatchRule {
	if m != nil {
		return m.MatchRules
	}
	return nil
}

func (m *Request) GetPathRule() string {
	if m != nil {
		return m.PathRule
	}
	return ""
}

func (m *Request) GetNeedMatchRule() string {
	if m != nil {
		return m.NeedMatchRule
	}
	return ""
}

type Response struct {
	Type                 ResponseType_Type `protobuf:"varint,1,opt,name=type,proto3,enum=types.ResponseType_Type" json:"type,omitempty"`
	MatchRules           []*MatchRule      `protobuf:"bytes,2,rep,name=MatchRules,proto3" json:"MatchRules,omitempty"`
	Data                 []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() ResponseType_Type {
	if m != nil {
		return m.Type
	}
	return ResponseType_ParserResult
}

func (m *Response) GetMatchRules() []*MatchRule {
	if m != nil {
		return m.MatchRules
	}
	return nil
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ParseResult struct {
	Code                 ClientResultCode_Code `protobuf:"varint,1,opt,name=code,proto3,enum=types.ClientResultCode_Code" json:"code,omitempty"`
	Requested            *Request              `protobuf:"bytes,2,opt,name=requested,proto3" json:"requested,omitempty"`
	Requests             []*Request            `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	Response             *Response             `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	ErrorMessage         string                `protobuf:"bytes,5,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ParseResult) Reset()         { *m = ParseResult{} }
func (m *ParseResult) String() string { return proto.CompactTextString(m) }
func (*ParseResult) ProtoMessage()    {}
func (*ParseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e8250c26998770a, []int{8}
}

func (m *ParseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResult.Unmarshal(m, b)
}
func (m *ParseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResult.Marshal(b, m, deterministic)
}
func (m *ParseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResult.Merge(m, src)
}
func (m *ParseResult) XXX_Size() int {
	return xxx_messageInfo_ParseResult.Size(m)
}
func (m *ParseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResult.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResult proto.InternalMessageInfo

func (m *ParseResult) GetCode() ClientResultCode_Code {
	if m != nil {
		return m.Code
	}
	return ClientResultCode_OK
}

func (m *ParseResult) GetRequested() *Request {
	if m != nil {
		return m.Requested
	}
	return nil
}

func (m *ParseResult) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *ParseResult) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ParseResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("types.ParserStatus_Status", ParserStatus_Status_name, ParserStatus_Status_value)
	proto.RegisterEnum("types.ParserType_Type", ParserType_Type_name, ParserType_Type_value)
	proto.RegisterEnum("types.ClientResultCode_Code", ClientResultCode_Code_name, ClientResultCode_Code_value)
	proto.RegisterEnum("types.RequestType_Type", RequestType_Type_name, RequestType_Type_value)
	proto.RegisterEnum("types.ResponseType_Type", ResponseType_Type_name, ResponseType_Type_value)
	proto.RegisterType((*ParserStatus)(nil), "types.ParserStatus")
	proto.RegisterType((*ParserType)(nil), "types.ParserType")
	proto.RegisterType((*ClientResultCode)(nil), "types.ClientResultCode")
	proto.RegisterType((*RequestType)(nil), "types.RequestType")
	proto.RegisterType((*ResponseType)(nil), "types.ResponseType")
	proto.RegisterType((*MatchRule)(nil), "types.MatchRule")
	proto.RegisterType((*Request)(nil), "types.Request")
	proto.RegisterType((*Response)(nil), "types.Response")
	proto.RegisterType((*ParseResult)(nil), "types.ParseResult")
}

func init() { proto.RegisterFile("package/types/protobuf.proto", fileDescriptor_6e8250c26998770a) }

var fileDescriptor_6e8250c26998770a = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x8d, 0x6c, 0x59, 0xb6, 0x46, 0xae, 0xb3, 0xcc, 0x21, 0x15, 0x21, 0x85, 0xb0, 0xe4, 0x10,
	0x9a, 0xa0, 0x18, 0x85, 0x42, 0x7b, 0x2a, 0xa9, 0x23, 0x8a, 0x48, 0x62, 0x9b, 0x8d, 0x4b, 0xe9,
	0x29, 0x28, 0xf6, 0x36, 0x2e, 0x71, 0x2d, 0x55, 0x2b, 0x15, 0x7c, 0xe9, 0xcf, 0xea, 0x8f, 0xea,
	0xaf, 0x28, 0xfb, 0x61, 0x59, 0x36, 0xed, 0x45, 0x3b, 0x33, 0x7a, 0xfb, 0x34, 0xef, 0xcd, 0x20,
	0x38, 0xca, 0x92, 0xe9, 0x73, 0xf2, 0xc4, 0x2f, 0x8a, 0x55, 0xc6, 0xc5, 0x45, 0x96, 0xa7, 0x45,
	0xfa, 0x58, 0x7e, 0x0d, 0x54, 0x80, 0x2d, 0x55, 0xa5, 0x03, 0xe8, 0x8e, 0x93, 0x5c, 0xf0, 0xfc,
	0xbe, 0x48, 0x8a, 0x52, 0xd0, 0x4b, 0x70, 0x74, 0x84, 0x6d, 0x68, 0x0e, 0xe3, 0x5b, 0xb2, 0x87,
	0x2e, 0xb4, 0x58, 0x74, 0x75, 0xfd, 0x85, 0x58, 0xe8, 0x41, 0xfb, 0xf3, 0x88, 0xdd, 0xc4, 0xc3,
	0x8f, 0xa4, 0x81, 0x1d, 0xb0, 0xaf, 0x47, 0xc3, 0x88, 0x34, 0xe9, 0x2b, 0x00, 0x4d, 0x32, 0x59,
	0x65, 0x9c, 0xee, 0x83, 0x2d, 0xcf, 0x8a, 0x80, 0xbe, 0x05, 0x32, 0x58, 0x7c, 0xe3, 0xcb, 0x82,
	0x71, 0x51, 0x2e, 0x8a, 0x41, 0x3a, 0xe3, 0xf4, 0x04, 0x6c, 0x79, 0xa2, 0x03, 0x8d, 0xd1, 0xcd,
	0xf6, 0x47, 0x5c, 0x68, 0x45, 0x8c, 0x8d, 0x18, 0x71, 0xe9, 0x7b, 0xf0, 0x18, 0xff, 0x51, 0x72,
	0x51, 0x28, 0xe6, 0xfe, 0x0e, 0x33, 0xee, 0x83, 0x37, 0xb8, 0x8d, 0xa3, 0xe1, 0xe4, 0x21, 0x1e,
	0xc6, 0x13, 0x62, 0x61, 0x0f, 0x60, 0x7c, 0xc5, 0xee, 0x23, 0xf6, 0xf0, 0x89, 0xdd, 0x12, 0xa0,
	0x31, 0x74, 0x19, 0x17, 0x59, 0xba, 0x14, 0x5c, 0x31, 0xbc, 0x33, 0x0c, 0x64, 0x2d, 0x5b, 0xb7,
	0x44, 0xf6, 0xd4, 0xcd, 0x54, 0x98, 0x16, 0x89, 0x25, 0xa9, 0xa3, 0x3c, 0x4f, 0xd7, 0x00, 0x97,
	0xde, 0x80, 0x7b, 0x97, 0x14, 0xd3, 0x39, 0x2b, 0x17, 0x1c, 0x11, 0xec, 0xbc, 0x5c, 0x70, 0xdf,
	0x3a, 0xb6, 0x4e, 0x5d, 0xa6, 0x62, 0x59, 0x7b, 0xe6, 0x2b, 0xe1, 0x37, 0x74, 0x4d, 0xc6, 0x78,
	0x00, 0xce, 0xcf, 0x64, 0x51, 0x72, 0xe1, 0x37, 0x55, 0xd5, 0x64, 0xf4, 0x77, 0x03, 0xda, 0x46,
	0x19, 0x86, 0xe0, 0x08, 0x65, 0xb9, 0x62, 0xeb, 0x85, 0x87, 0x81, 0x1a, 0x4d, 0x50, 0x9f, 0x4b,
	0xa0, 0x0f, 0x66, 0x90, 0x18, 0x80, 0x93, 0xa9, 0xd7, 0xea, 0x6b, 0xbd, 0xf0, 0x60, 0xeb, 0x8e,
	0x94, 0x18, 0xc8, 0x07, 0x33, 0x28, 0x3c, 0x03, 0x5b, 0x02, 0x54, 0x17, 0xbd, 0xf0, 0xa5, 0x41,
	0xd7, 0xbc, 0xd5, 0x70, 0x05, 0x92, 0x42, 0xe6, 0xa9, 0x28, 0x7c, 0x5b, 0x0b, 0x91, 0xb1, 0xac,
	0x65, 0x49, 0x31, 0xf7, 0x5b, 0xba, 0x26, 0x63, 0xec, 0x03, 0x7c, 0x5f, 0x3b, 0x22, 0x7c, 0xe7,
	0xb8, 0x79, 0xea, 0x85, 0xc4, 0x50, 0x57, 0x56, 0xb1, 0x1a, 0x06, 0x0f, 0xa1, 0x23, 0x6f, 0xca,
	0xc4, 0x6f, 0x2b, 0xa6, 0x2a, 0xc7, 0x13, 0x78, 0xb1, 0xe4, 0x7c, 0x56, 0x5d, 0xf4, 0x3b, 0x0a,
	0xb0, 0x5d, 0xa4, 0xbf, 0xa0, 0xb3, 0x1e, 0x28, 0x9e, 0x1b, 0x51, 0xda, 0x36, 0xbf, 0x12, 0xb5,
	0x99, 0x77, 0x5d, 0x55, 0x1f, 0xe0, 0x6e, 0xd3, 0x6d, 0xe3, 0x7f, 0xdd, 0x6e, 0x30, 0x52, 0xf3,
	0x2c, 0x29, 0x12, 0x65, 0x5a, 0x97, 0xa9, 0x98, 0xfe, 0xb1, 0xc0, 0x53, 0x26, 0xeb, 0xbd, 0xc0,
	0x3e, 0xd8, 0xd3, 0x74, 0xb6, 0xee, 0xe1, 0xc8, 0xf0, 0xed, 0xae, 0x7b, 0x20, 0x1f, 0x4c, 0x21,
	0xf1, 0x1c, 0xdc, 0x5c, 0xfb, 0xce, 0x67, 0x6a, 0x7a, 0x5e, 0xd8, 0xdb, 0x9e, 0x07, 0xdb, 0x00,
	0xf0, 0x35, 0x74, 0x4c, 0x22, 0x57, 0xa8, 0xf9, 0x0f, 0x70, 0xf5, 0x1e, 0xcf, 0x24, 0x56, 0x8b,
	0x57, 0xb3, 0xf3, 0xc2, 0xfd, 0x1d, 0x4f, 0x58, 0x05, 0x40, 0x0a, 0x5d, 0x2e, 0xf7, 0xfb, 0x8e,
	0x0b, 0x91, 0x3c, 0x71, 0x33, 0xd8, 0xad, 0x5a, 0xf8, 0x01, 0xdc, 0x71, 0x9e, 0x4e, 0xb9, 0x10,
	0x69, 0x8e, 0x6f, 0xea, 0x09, 0xd6, 0xf7, 0x4d, 0xeb, 0x3c, 0xdc, 0x69, 0x8c, 0xee, 0x9d, 0x5a,
	0x7d, 0xeb, 0xd1, 0x51, 0xbf, 0x9b, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0x50, 0xbf,
	0xa3, 0x8e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcessorClient is the client API for Processor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessorClient interface {
	Processor(ctx context.Context, opts ...grpc.CallOption) (Processor_ProcessorClient, error)
}

type processorClient struct {
	cc *grpc.ClientConn
}

func NewProcessorClient(cc *grpc.ClientConn) ProcessorClient {
	return &processorClient{cc}
}

func (c *processorClient) Processor(ctx context.Context, opts ...grpc.CallOption) (Processor_ProcessorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Processor_serviceDesc.Streams[0], "/types.Processor/Processor", opts...)
	if err != nil {
		return nil, err
	}
	x := &processorProcessorClient{stream}
	return x, nil
}

type Processor_ProcessorClient interface {
	Send(*ParseResult) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type processorProcessorClient struct {
	grpc.ClientStream
}

func (x *processorProcessorClient) Send(m *ParseResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *processorProcessorClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProcessorServer is the server API for Processor service.
type ProcessorServer interface {
	Processor(Processor_ProcessorServer) error
}

// UnimplementedProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedProcessorServer struct {
}

func (*UnimplementedProcessorServer) Processor(srv Processor_ProcessorServer) error {
	return status.Errorf(codes.Unimplemented, "method Processor not implemented")
}

func RegisterProcessorServer(s *grpc.Server, srv ProcessorServer) {
	s.RegisterService(&_Processor_serviceDesc, srv)
}

func _Processor_Processor_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorServer).Processor(&processorProcessorServer{stream})
}

type Processor_ProcessorServer interface {
	Send(*Request) error
	Recv() (*ParseResult, error)
	grpc.ServerStream
}

type processorProcessorServer struct {
	grpc.ServerStream
}

func (x *processorProcessorServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *processorProcessorServer) Recv() (*ParseResult, error) {
	m := new(ParseResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Processor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.Processor",
	HandlerType: (*ProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Processor",
			Handler:       _Processor_Processor_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "package/types/protobuf.proto",
}
